### PR TITLE
Allow running on save to be toggled on or off.

### PR DESCRIPTION
**Pull request by Wilfred**
Fixes https://github.com/fbergroth/emacs-rustfmt/issues/7

### CODE REVIEW

**Comment by fbergroth** [comment]
Thank you! Maybe it's better to just add a function `rustfmt-disable-on-save`, so that calling `rustfmt-enable-on-save` twice won't actually disable it?

If you want a toggle as well, you can add `rustfmt-toggle-on-save`, but having `rustfmt-disable-on-save` might be sufficient.

**Comment by fbergroth** [comment]
@Wilfred ping :-)

**Comment by Wilfred** [comment]
Hm, thinking about this some more, how about making it a minor mode? `rustfmt-on-save-mode` seems a natural Emacsy solution to toggling on and off.

**Comment by fbergroth** [comment]
Sounds good!

**Comment by Wilfred** [comment]
Groovy. I'll send a separate pull request.

**Pull request closed without merging**
