### PR TITLE
Fix rustfmt not finding modules

### PR DESCRIPTION
**Pull request by bryal**
The temporary file that rustfmt edits is created in 'temporary-file-directory', which is by default '/tmp'. Since rustfmt looks for module source in locations relative to the working file, this causes problems.

This commit fixes rustfmt not finding modules, by changing the dir where to create the working file to the same as the dir of the original .rs file.

### CODE REVIEW

**Comment by fbergroth** [comment]
Thanks!

Currently I'm passing `--write-mode=overwrite`. With this change, I guess that rustfmt may overwrite other source files, which is problematic if the user have unsaved buffers.

I see that rustfmt now has added support to receive input via stdin, so that may be a better option. Would you like to work on that? Otherwise I may have some free time later today.

**Comment by bryal** [comment]
I had not really considered this, but I don't think it would be a problem.
If a file is changed on disk outside of Emacs, Emacs will prompt the user to either keep the current buffer, or reload the file from disk.

I might be missing something, but I now believe the creation of a temporary working file isn't necessary in the first place.

**Comment by fbergroth** [comment]
Well, I consider it bad behavior if this package modifies other buffers.

Right. When I wrote this package, it wasn't possible to send the code via stdin to rustfmt. That is now possible, and this package should adapt to use it.

**Comment by bryal** [comment]
Ok. I just tried using rustfmt with input from stdin, and agree that it is a much cleaner option.
I'll try implementing this behaviour

**Comment by fbergroth** [comment]
Cools, open another PR when it's ready :smile:

**Pull request closed without merging**
