### PR TITLE
Display/hide errors buffer.

### PR DESCRIPTION
**Pull request by ckoparkar**
The previous `rustfmt--call` function, silently saved the file, even if the process encounters an error. This should fix that. Also, we kill the errors buffer after successful fmt execution.

### CODE REVIEW

**Comment by ckoparkar** [comment]
Your thoughts @fbergroth ?

**Comment by fbergroth** [comment]
Hang on, I'll review your PR in a couple of hours.

**Comment by fbergroth** [comment]
Thanks for your contribution!

> The previous rustfmt--call function, silently saved the file, even if the process encounters an error.

Well, no - `rustfmt--call` never saves the buffer. I guess you mean that if you add `rustfmt-format-buffer` to the `before-save-hook`, then you won't notice failures, that is true. When I wrote this code, `rustfmt` was not reliable enough to be used that way, but it seems much better now, so this is a good feature.

Regarding your code, there were a couple of problems:
- You use tabs instead of spaces.
- `get-buffer-create` never returns `nil`, so no need to check for that.
- It is better to add a hook to `rust-mode-hook` that sets a local `before-save-hook`.
- I prefer not to delete windows from the user.

I added your commit with some changes in 9fe3ffed33ded6d4dc073647d65329aa4382eeff. Please have a look! :smile:

**Comment by fbergroth** [comment]
Regarding your PR to the main `rustfmt` repo, I'd prefer if you directly linked to this repository, and maybe added another link to the tutorial for beginners.

**Comment by ckoparkar** [comment]
Thanks @fbergroth. This was my first public elisp code.

> You use tabs instead of spaces. `get-buffer-create` never returns `nil`, so no need to check for that.

Ill be more careful  from next time. :smile: 

>  I'd prefer if you directly linked to this repository

The gist actually has a link to this repository. But yeah, now that the integration is just a one liner, it makes sense to directly link it here. I'll change it.

> I prefer not to delete windows from the user.

I agree, but in this case we could consider it as we are creating the window. Suppose a user is editing the file and the error buffer pops up. He corrects the `.rs` file and re-runs the save hook. The `errors` buffer is killed but the window persists and is replaced by some other open buffer. IMHO this would be the right behaviour if the user was using split windows to begin with, not otherwise.

Also it would be really great if the cursor is automatically transferred to the `*.rs` buffer. There's no work to be done in the errors buffer anyways.

**Comment by fbergroth** [comment]
> I agree, but in this case we could consider it as we are creating the window. Suppose a user is editing the file and the error buffer pops up. He corrects the .rs file and re-runs the save hook. The errors buffer is killed but the window persists and is replaced by some other open buffer. IMHO this would be the right behaviour if the user was using split windows to begin with, not otherwise.

Right, I think the user should use [shackle](https://github.com/wasamasa/shackle) (or [popwin](https://github.com/m2ym/popwin-el)) to get a better pop-up behaviour. Killing an existing window is too intrusive.

> Also it would be really great if the cursor is automatically transferred to the *.rs buffer. There's no work to be done in the errors buffer anyways.

If the error buffer is active, the user can press `RET` to jump to the error or `q` to close the window. It's configurable in `shackle` with the `:noselect t` rule. I can add an example in the readme later on.

**Comment by ckoparkar** [comment]
Cool. The `RET` behaviour is useful :smile:

**Pull request closed without merging**
